version: "3"
services:
    web:
        build: .
        ports:
            - "8080:80"
            - "80:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "HelloWorld1a!"
            ACCEPT_EULA: "Y"
